---
apiVersion: scheduler.config.gardener.cloud/v1alpha1
kind: SchedulerConfiguration
clientConnection:
  qps: 100
  burst: 130
leaderElection:
  leaderElect: true
  leaseDuration: 15s
  renewDeadline: 10s
  retryPeriod: 2s
  resourceLock: leases
  resourceNamespace: garden
logLevel: info
healthServer:
  http:
    bindAddress: 0.0.0.0
    port: 10251
metricsServer:
  http:
    bindAddress: 0.0.0.0
    port: 19251
#schedulers:
#  backupBucket:
#    concurrentSyncs: 5 # defaults to 5
#  shoot:
#    concurrentSyncs: 5 # defaults to 5
#    candidateDeterminationStrategy: MinimalDistance # either {SameRegion,MinimalDistance}
featureGates:
  CachedRuntimeClients: true
